config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :nightmares
  root to: 'nightmares#index'

end

app/models/nightmare.rb
class Nightmare < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :profile_name, presence: true,
  						   uniqueness: true

  has_many :nightmares
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/nightmares_controller.rb
class NightmaresController < ApplicationController
  before_action :set_nightmare, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /nightmares
  # GET /nightmares.json
  def index
    @nightmares = Nightmare.all
  end

  # GET /nightmares/1
  # GET /nightmares/1.json
  def show
  end

  # GET /nightmares/new
  def new
    @nightmare = Nightmare.new
  end

  # GET /nightmares/1/edit
  def edit
  end

  # POST /nightmares
  # POST /nightmares.json
  def create
    @nightmare = Nightmare.new(nightmare_params)

    respond_to do |format|
      if @nightmare.save
        format.html { redirect_to @nightmare }
        format.json { render :show, status: :created, location: @nightmare }
      else
        format.html { render :new }
        format.json { render json: @nightmare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nightmares/1
  # PATCH/PUT /nightmares/1.json
  def update
    respond_to do |format|
      if @nightmare.update(nightmare_params)
        format.html { redirect_to @nightmare, notice: 'Nightmare updated.' }
        format.json { render :show, status: :ok, location: @nightmare }
      else
        format.html { render :edit }
        format.json { render json: @nightmare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nightmares/1
  # DELETE /nightmares/1.json
  def destroy
    @nightmare.destroy
    respond_to do |format|
      format.html { redirect_to nightmares_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nightmare
      @nightmare = Nightmare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nightmare_params
      params.require(:nightmare).permit(:name, :expression, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nightmares_helper.rb
module NightmaresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NightmareGerman</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Nightmare German</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li>
                <li><%= link_to "Nightmares", nightmares_path%></li>
              </li>
            </ul>
            <ul class="nav pull-right">
					
					<% if user_signed_in? then %>
						<li>
						<%= link_to current_user.name, edit_user_registration_path %>
						</li>
						
						<li>
							<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
						</li>
						<% else %>
						<li>
							<%= link_to('Register', new_user_registration_path) %>
						</li>
						<li>
							<%= link_to('Login', new_user_session_path) %>
						</li>
					<% end %>
				</ul>
          </div>
        </div>
      </div>
    </div>

	<div class="container">
		<p class="notice"><%= notice %></p>
<!-- 		<p class="alert"><%= alert %></p> -->
		<%= yield %>
	</div>

</body>
</html>

app/views/nightmares/_form.html.erb
<%= simple_form_for(@nightmare, html: {class: "form-horizontal"}) do |f| %>
  <% if @nightmare.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nightmare.errors.count, "error") %> prohibited this nightmare from being saved:</h2>

      <ul>
      <% @nightmare.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :user_id, collection: User.all, label_method: :name %>
  <%= f.input :expression %>
  <%= f.input :description %>

  <div class="form-actions">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/nightmares/edit.html.erb
<h1>Edit Nightmare</h1>

<%= render 'form' %>

<%= link_to 'Show', @nightmare %> |
<%= link_to 'Back', nightmares_path %>

app/views/nightmares/index.html.erb
<div class="page-header">
  <h2>Words which cause nightmares:</h2>
</div>

<%= link_to "Post a New Nightmare", new_nightmare_path, class:"btn btn-primary" %>
<br>
<br>
<% @nightmares.each do |nightmare|%>
  <div class="nightmare" >
    <% if nightmare.user.present?%>
      <strong><%= nightmare.user.name%></strong>
    <% end %>
    <p><%= nightmare.expression%> : <em><%= nightmare.description%></em></p>
    <div class="meta">
      <%= link_to time_ago_in_words(nightmare.created_at) + " ago", nightmare%>
      <% if user_signed_in? then %>
      <span class="admin">
       | <%= link_to 'Edit', edit_nightmare_path(nightmare)%> | 
        <%= link_to 'Destroy', nightmare, method: :delete, data: {confirm:"Are you sure you want to delete this?"}%>
      </span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/nightmares/new.html.erb
<h1>New Nightmare</h1>

<%= render 'form' %>

<%= link_to 'Back', nightmares_path %>

app/views/nightmares/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <% if @nightmare.user.present?%>
  <%= @nightmare.user.name%>
  <% end %>
</p>

<p>
  <strong>Expression:</strong>
  <%= @nightmare.expression %>
</p>

<p>
  <strong>Description:</strong>
  <%= @nightmare.description %>
</p>

<% if user_signed_in? then %>
<%= link_to 'Edit', edit_nightmare_path(@nightmare) %> |
<% end %>
<%= link_to 'Back', nightmares_path %>